# Generated by Django 3.2.5 on 2021-07-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
    ]
